/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * AnniversaryDateFilterOperator - Operators for anniversary date filters.
 */
public enum AnniversaryDateFilterOperator {
    ANNIVERSARY("anniversary"),
    ANNIVERSARY_MONTH("anniversary-month");

    @JsonValue
    private final String value;

    private AnniversaryDateFilterOperator(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
