/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;


import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;


public class CampaignRecipientEstimationResponseObjectResourceAttributes {

    /**
     * The estimated number of unique recipients the campaign will send to
     */
    @JsonProperty("estimated_recipient_count")
    private long estimatedRecipientCount;

    @JsonCreator
    public CampaignRecipientEstimationResponseObjectResourceAttributes(
            @JsonProperty("estimated_recipient_count") long estimatedRecipientCount) {
        Utils.checkNotNull(estimatedRecipientCount, "estimatedRecipientCount");
        this.estimatedRecipientCount = estimatedRecipientCount;
    }

    /**
     * The estimated number of unique recipients the campaign will send to
     */
    @JsonIgnore
    public long estimatedRecipientCount() {
        return estimatedRecipientCount;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The estimated number of unique recipients the campaign will send to
     */
    public CampaignRecipientEstimationResponseObjectResourceAttributes withEstimatedRecipientCount(long estimatedRecipientCount) {
        Utils.checkNotNull(estimatedRecipientCount, "estimatedRecipientCount");
        this.estimatedRecipientCount = estimatedRecipientCount;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CampaignRecipientEstimationResponseObjectResourceAttributes other = (CampaignRecipientEstimationResponseObjectResourceAttributes) o;
        return 
            Objects.deepEquals(this.estimatedRecipientCount, other.estimatedRecipientCount);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            estimatedRecipientCount);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CampaignRecipientEstimationResponseObjectResourceAttributes.class,
                "estimatedRecipientCount", estimatedRecipientCount);
    }
    
    public final static class Builder {
 
        private Long estimatedRecipientCount;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The estimated number of unique recipients the campaign will send to
         */
        public Builder estimatedRecipientCount(long estimatedRecipientCount) {
            Utils.checkNotNull(estimatedRecipientCount, "estimatedRecipientCount");
            this.estimatedRecipientCount = estimatedRecipientCount;
            return this;
        }
        
        public CampaignRecipientEstimationResponseObjectResourceAttributes build() {
            return new CampaignRecipientEstimationResponseObjectResourceAttributes(
                estimatedRecipientCount);
        }
    }
}

