/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;


import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;


public class CampaignMessageAssignTemplateQueryResourceObject {

    @JsonProperty("type")
    private CampaignMessageEnum type;

    /**
     * The message ID to be assigned to
     */
    @JsonProperty("id")
    private String id;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("relationships")
    private Optional<? extends Relationships> relationships;

    @JsonCreator
    public CampaignMessageAssignTemplateQueryResourceObject(
            @JsonProperty("type") CampaignMessageEnum type,
            @JsonProperty("id") String id,
            @JsonProperty("relationships") Optional<? extends Relationships> relationships) {
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(relationships, "relationships");
        this.type = type;
        this.id = id;
        this.relationships = relationships;
    }
    
    public CampaignMessageAssignTemplateQueryResourceObject(
            CampaignMessageEnum type,
            String id) {
        this(type, id, Optional.empty());
    }

    @JsonIgnore
    public CampaignMessageEnum type() {
        return type;
    }

    /**
     * The message ID to be assigned to
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Relationships> relationships() {
        return (Optional<Relationships>) relationships;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CampaignMessageAssignTemplateQueryResourceObject withType(CampaignMessageEnum type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    /**
     * The message ID to be assigned to
     */
    public CampaignMessageAssignTemplateQueryResourceObject withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public CampaignMessageAssignTemplateQueryResourceObject withRelationships(Relationships relationships) {
        Utils.checkNotNull(relationships, "relationships");
        this.relationships = Optional.ofNullable(relationships);
        return this;
    }

    public CampaignMessageAssignTemplateQueryResourceObject withRelationships(Optional<? extends Relationships> relationships) {
        Utils.checkNotNull(relationships, "relationships");
        this.relationships = relationships;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CampaignMessageAssignTemplateQueryResourceObject other = (CampaignMessageAssignTemplateQueryResourceObject) o;
        return 
            Objects.deepEquals(this.type, other.type) &&
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.relationships, other.relationships);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            type,
            id,
            relationships);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CampaignMessageAssignTemplateQueryResourceObject.class,
                "type", type,
                "id", id,
                "relationships", relationships);
    }
    
    public final static class Builder {
 
        private CampaignMessageEnum type;
 
        private String id;
 
        private Optional<? extends Relationships> relationships = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder type(CampaignMessageEnum type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }

        /**
         * The message ID to be assigned to
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        public Builder relationships(Relationships relationships) {
            Utils.checkNotNull(relationships, "relationships");
            this.relationships = Optional.ofNullable(relationships);
            return this;
        }

        public Builder relationships(Optional<? extends Relationships> relationships) {
            Utils.checkNotNull(relationships, "relationships");
            this.relationships = relationships;
            return this;
        }
        
        public CampaignMessageAssignTemplateQueryResourceObject build() {
            return new CampaignMessageAssignTemplateQueryResourceObject(
                type,
                id,
                relationships);
        }
    }
}

