/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;


import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;


public class CatalogCategoryUpdateQueryResourceObjectAttributes {

    /**
     * The name of the catalog category.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private JsonNullable<String> name;

    @JsonCreator
    public CatalogCategoryUpdateQueryResourceObjectAttributes(
            @JsonProperty("name") JsonNullable<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
    }
    
    public CatalogCategoryUpdateQueryResourceObjectAttributes() {
        this(JsonNullable.undefined());
    }

    /**
     * The name of the catalog category.
     */
    @JsonIgnore
    public JsonNullable<String> name() {
        return name;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The name of the catalog category.
     */
    public CatalogCategoryUpdateQueryResourceObjectAttributes withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = JsonNullable.of(name);
        return this;
    }

    /**
     * The name of the catalog category.
     */
    public CatalogCategoryUpdateQueryResourceObjectAttributes withName(JsonNullable<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CatalogCategoryUpdateQueryResourceObjectAttributes other = (CatalogCategoryUpdateQueryResourceObjectAttributes) o;
        return 
            Objects.deepEquals(this.name, other.name);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            name);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CatalogCategoryUpdateQueryResourceObjectAttributes.class,
                "name", name);
    }
    
    public final static class Builder {
 
        private JsonNullable<String> name = JsonNullable.undefined();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the catalog category.
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = JsonNullable.of(name);
            return this;
        }

        /**
         * The name of the catalog category.
         */
        public Builder name(JsonNullable<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }
        
        public CatalogCategoryUpdateQueryResourceObjectAttributes build() {
            return new CatalogCategoryUpdateQueryResourceObjectAttributes(
                name);
        }
    }
}

