/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;


import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;


public class GetCampaignResponseRelationships {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("campaign-messages")
    private Optional<? extends GetCampaignResponseCampaignMessages> campaignMessages;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tags")
    private Optional<? extends GetCampaignResponseTags> tags;

    @JsonCreator
    public GetCampaignResponseRelationships(
            @JsonProperty("campaign-messages") Optional<? extends GetCampaignResponseCampaignMessages> campaignMessages,
            @JsonProperty("tags") Optional<? extends GetCampaignResponseTags> tags) {
        Utils.checkNotNull(campaignMessages, "campaignMessages");
        Utils.checkNotNull(tags, "tags");
        this.campaignMessages = campaignMessages;
        this.tags = tags;
    }
    
    public GetCampaignResponseRelationships() {
        this(Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetCampaignResponseCampaignMessages> campaignMessages() {
        return (Optional<GetCampaignResponseCampaignMessages>) campaignMessages;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetCampaignResponseTags> tags() {
        return (Optional<GetCampaignResponseTags>) tags;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public GetCampaignResponseRelationships withCampaignMessages(GetCampaignResponseCampaignMessages campaignMessages) {
        Utils.checkNotNull(campaignMessages, "campaignMessages");
        this.campaignMessages = Optional.ofNullable(campaignMessages);
        return this;
    }

    public GetCampaignResponseRelationships withCampaignMessages(Optional<? extends GetCampaignResponseCampaignMessages> campaignMessages) {
        Utils.checkNotNull(campaignMessages, "campaignMessages");
        this.campaignMessages = campaignMessages;
        return this;
    }

    public GetCampaignResponseRelationships withTags(GetCampaignResponseTags tags) {
        Utils.checkNotNull(tags, "tags");
        this.tags = Optional.ofNullable(tags);
        return this;
    }

    public GetCampaignResponseRelationships withTags(Optional<? extends GetCampaignResponseTags> tags) {
        Utils.checkNotNull(tags, "tags");
        this.tags = tags;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetCampaignResponseRelationships other = (GetCampaignResponseRelationships) o;
        return 
            Objects.deepEquals(this.campaignMessages, other.campaignMessages) &&
            Objects.deepEquals(this.tags, other.tags);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            campaignMessages,
            tags);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetCampaignResponseRelationships.class,
                "campaignMessages", campaignMessages,
                "tags", tags);
    }
    
    public final static class Builder {
 
        private Optional<? extends GetCampaignResponseCampaignMessages> campaignMessages = Optional.empty();
 
        private Optional<? extends GetCampaignResponseTags> tags = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder campaignMessages(GetCampaignResponseCampaignMessages campaignMessages) {
            Utils.checkNotNull(campaignMessages, "campaignMessages");
            this.campaignMessages = Optional.ofNullable(campaignMessages);
            return this;
        }

        public Builder campaignMessages(Optional<? extends GetCampaignResponseCampaignMessages> campaignMessages) {
            Utils.checkNotNull(campaignMessages, "campaignMessages");
            this.campaignMessages = campaignMessages;
            return this;
        }

        public Builder tags(GetCampaignResponseTags tags) {
            Utils.checkNotNull(tags, "tags");
            this.tags = Optional.ofNullable(tags);
            return this;
        }

        public Builder tags(Optional<? extends GetCampaignResponseTags> tags) {
            Utils.checkNotNull(tags, "tags");
            this.tags = tags;
            return this;
        }
        
        public GetCampaignResponseRelationships build() {
            return new GetCampaignResponseRelationships(
                campaignMessages,
                tags);
        }
    }
}

