/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;


import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class GetReviewResponseDto20240715CompoundDocument {

    @JsonProperty("data")
    private GetReviewResponseDto20240715CompoundDocumentData data;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("included")
    private Optional<? extends List<EventResponseObjectResource>> included;

    @JsonCreator
    public GetReviewResponseDto20240715CompoundDocument(
            @JsonProperty("data") GetReviewResponseDto20240715CompoundDocumentData data,
            @JsonProperty("included") Optional<? extends List<EventResponseObjectResource>> included) {
        Utils.checkNotNull(data, "data");
        Utils.checkNotNull(included, "included");
        this.data = data;
        this.included = included;
    }
    
    public GetReviewResponseDto20240715CompoundDocument(
            GetReviewResponseDto20240715CompoundDocumentData data) {
        this(data, Optional.empty());
    }

    @JsonIgnore
    public GetReviewResponseDto20240715CompoundDocumentData data() {
        return data;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<EventResponseObjectResource>> included() {
        return (Optional<List<EventResponseObjectResource>>) included;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public GetReviewResponseDto20240715CompoundDocument withData(GetReviewResponseDto20240715CompoundDocumentData data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }

    public GetReviewResponseDto20240715CompoundDocument withIncluded(List<EventResponseObjectResource> included) {
        Utils.checkNotNull(included, "included");
        this.included = Optional.ofNullable(included);
        return this;
    }

    public GetReviewResponseDto20240715CompoundDocument withIncluded(Optional<? extends List<EventResponseObjectResource>> included) {
        Utils.checkNotNull(included, "included");
        this.included = included;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetReviewResponseDto20240715CompoundDocument other = (GetReviewResponseDto20240715CompoundDocument) o;
        return 
            Objects.deepEquals(this.data, other.data) &&
            Objects.deepEquals(this.included, other.included);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            data,
            included);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetReviewResponseDto20240715CompoundDocument.class,
                "data", data,
                "included", included);
    }
    
    public final static class Builder {
 
        private GetReviewResponseDto20240715CompoundDocumentData data;
 
        private Optional<? extends List<EventResponseObjectResource>> included = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder data(GetReviewResponseDto20240715CompoundDocumentData data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }

        public Builder included(List<EventResponseObjectResource> included) {
            Utils.checkNotNull(included, "included");
            this.included = Optional.ofNullable(included);
            return this;
        }

        public Builder included(Optional<? extends List<EventResponseObjectResource>> included) {
            Utils.checkNotNull(included, "included");
            this.included = included;
            return this;
        }
        
        public GetReviewResponseDto20240715CompoundDocument build() {
            return new GetReviewResponseDto20240715CompoundDocument(
                data,
                included);
        }
    }
}

