/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;


import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;


public class PatchListPartialUpdateResponseRelationships {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("profiles")
    private Optional<? extends PatchListPartialUpdateResponseProfiles> profiles;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tags")
    private Optional<? extends PatchListPartialUpdateResponseTags> tags;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("flow-triggers")
    private Optional<? extends PatchListPartialUpdateResponseFlowTriggers> flowTriggers;

    @JsonCreator
    public PatchListPartialUpdateResponseRelationships(
            @JsonProperty("profiles") Optional<? extends PatchListPartialUpdateResponseProfiles> profiles,
            @JsonProperty("tags") Optional<? extends PatchListPartialUpdateResponseTags> tags,
            @JsonProperty("flow-triggers") Optional<? extends PatchListPartialUpdateResponseFlowTriggers> flowTriggers) {
        Utils.checkNotNull(profiles, "profiles");
        Utils.checkNotNull(tags, "tags");
        Utils.checkNotNull(flowTriggers, "flowTriggers");
        this.profiles = profiles;
        this.tags = tags;
        this.flowTriggers = flowTriggers;
    }
    
    public PatchListPartialUpdateResponseRelationships() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PatchListPartialUpdateResponseProfiles> profiles() {
        return (Optional<PatchListPartialUpdateResponseProfiles>) profiles;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PatchListPartialUpdateResponseTags> tags() {
        return (Optional<PatchListPartialUpdateResponseTags>) tags;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PatchListPartialUpdateResponseFlowTriggers> flowTriggers() {
        return (Optional<PatchListPartialUpdateResponseFlowTriggers>) flowTriggers;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public PatchListPartialUpdateResponseRelationships withProfiles(PatchListPartialUpdateResponseProfiles profiles) {
        Utils.checkNotNull(profiles, "profiles");
        this.profiles = Optional.ofNullable(profiles);
        return this;
    }

    public PatchListPartialUpdateResponseRelationships withProfiles(Optional<? extends PatchListPartialUpdateResponseProfiles> profiles) {
        Utils.checkNotNull(profiles, "profiles");
        this.profiles = profiles;
        return this;
    }

    public PatchListPartialUpdateResponseRelationships withTags(PatchListPartialUpdateResponseTags tags) {
        Utils.checkNotNull(tags, "tags");
        this.tags = Optional.ofNullable(tags);
        return this;
    }

    public PatchListPartialUpdateResponseRelationships withTags(Optional<? extends PatchListPartialUpdateResponseTags> tags) {
        Utils.checkNotNull(tags, "tags");
        this.tags = tags;
        return this;
    }

    public PatchListPartialUpdateResponseRelationships withFlowTriggers(PatchListPartialUpdateResponseFlowTriggers flowTriggers) {
        Utils.checkNotNull(flowTriggers, "flowTriggers");
        this.flowTriggers = Optional.ofNullable(flowTriggers);
        return this;
    }

    public PatchListPartialUpdateResponseRelationships withFlowTriggers(Optional<? extends PatchListPartialUpdateResponseFlowTriggers> flowTriggers) {
        Utils.checkNotNull(flowTriggers, "flowTriggers");
        this.flowTriggers = flowTriggers;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PatchListPartialUpdateResponseRelationships other = (PatchListPartialUpdateResponseRelationships) o;
        return 
            Objects.deepEquals(this.profiles, other.profiles) &&
            Objects.deepEquals(this.tags, other.tags) &&
            Objects.deepEquals(this.flowTriggers, other.flowTriggers);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            profiles,
            tags,
            flowTriggers);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PatchListPartialUpdateResponseRelationships.class,
                "profiles", profiles,
                "tags", tags,
                "flowTriggers", flowTriggers);
    }
    
    public final static class Builder {
 
        private Optional<? extends PatchListPartialUpdateResponseProfiles> profiles = Optional.empty();
 
        private Optional<? extends PatchListPartialUpdateResponseTags> tags = Optional.empty();
 
        private Optional<? extends PatchListPartialUpdateResponseFlowTriggers> flowTriggers = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder profiles(PatchListPartialUpdateResponseProfiles profiles) {
            Utils.checkNotNull(profiles, "profiles");
            this.profiles = Optional.ofNullable(profiles);
            return this;
        }

        public Builder profiles(Optional<? extends PatchListPartialUpdateResponseProfiles> profiles) {
            Utils.checkNotNull(profiles, "profiles");
            this.profiles = profiles;
            return this;
        }

        public Builder tags(PatchListPartialUpdateResponseTags tags) {
            Utils.checkNotNull(tags, "tags");
            this.tags = Optional.ofNullable(tags);
            return this;
        }

        public Builder tags(Optional<? extends PatchListPartialUpdateResponseTags> tags) {
            Utils.checkNotNull(tags, "tags");
            this.tags = tags;
            return this;
        }

        public Builder flowTriggers(PatchListPartialUpdateResponseFlowTriggers flowTriggers) {
            Utils.checkNotNull(flowTriggers, "flowTriggers");
            this.flowTriggers = Optional.ofNullable(flowTriggers);
            return this;
        }

        public Builder flowTriggers(Optional<? extends PatchListPartialUpdateResponseFlowTriggers> flowTriggers) {
            Utils.checkNotNull(flowTriggers, "flowTriggers");
            this.flowTriggers = flowTriggers;
            return this;
        }
        
        public PatchListPartialUpdateResponseRelationships build() {
            return new PatchListPartialUpdateResponseRelationships(
                profiles,
                tags,
                flowTriggers);
        }
    }
}

