/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * PushTokenUnregisterQueryResourceObjectPlatform - The platform on which the push token was created.
 */
public enum PushTokenUnregisterQueryResourceObjectPlatform {
    ANDROID("android"),
    IOS("ios");

    @JsonValue
    private final String value;

    private PushTokenUnregisterQueryResourceObjectPlatform(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
