/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.components;


import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;


public class SMSContentSubObjectCreate {

    /**
     * The message body
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("body")
    private JsonNullable<String> body;

    @JsonCreator
    public SMSContentSubObjectCreate(
            @JsonProperty("body") JsonNullable<String> body) {
        Utils.checkNotNull(body, "body");
        this.body = body;
    }
    
    public SMSContentSubObjectCreate() {
        this(JsonNullable.undefined());
    }

    /**
     * The message body
     */
    @JsonIgnore
    public JsonNullable<String> body() {
        return body;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The message body
     */
    public SMSContentSubObjectCreate withBody(String body) {
        Utils.checkNotNull(body, "body");
        this.body = JsonNullable.of(body);
        return this;
    }

    /**
     * The message body
     */
    public SMSContentSubObjectCreate withBody(JsonNullable<String> body) {
        Utils.checkNotNull(body, "body");
        this.body = body;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SMSContentSubObjectCreate other = (SMSContentSubObjectCreate) o;
        return 
            Objects.deepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SMSContentSubObjectCreate.class,
                "body", body);
    }
    
    public final static class Builder {
 
        private JsonNullable<String> body = JsonNullable.undefined();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The message body
         */
        public Builder body(String body) {
            Utils.checkNotNull(body, "body");
            this.body = JsonNullable.of(body);
            return this;
        }

        /**
         * The message body
         */
        public Builder body(JsonNullable<String> body) {
            Utils.checkNotNull(body, "body");
            this.body = body;
            return this;
        }
        
        public SMSContentSubObjectCreate build() {
            return new SMSContentSubObjectCreate(
                body);
        }
    }
}

