workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Klaviyo API:
        inputs:
            - location: ../stable-2.json
        registry:
            location: registry.speakeasyapi.dev/cs-pzi/cs/klaviyo-api
targets:
    klaviyo-java:
        target: java
        source: Klaviyo API
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cs-pzi/cs/klaviyo-api-code-samples
            blocking: false
