/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-10-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ContentRepeat
 */



public class ContentRepeat {
  @SerializedName("repeat_for")
  private String repeatFor = null;

  @SerializedName("item_alias")
  private String itemAlias = null;

  public ContentRepeat repeatFor(String repeatFor) {
    this.repeatFor = repeatFor;
    return this;
  }

   /**
   * Get repeatFor
   * @return repeatFor
  **/
  @Schema(required = true, description = "")
  public String getRepeatFor() {
    return repeatFor;
  }

  public void setRepeatFor(String repeatFor) {
    this.repeatFor = repeatFor;
  }

  public ContentRepeat itemAlias(String itemAlias) {
    this.itemAlias = itemAlias;
    return this;
  }

   /**
   * Get itemAlias
   * @return itemAlias
  **/
  @Schema(required = true, description = "")
  public String getItemAlias() {
    return itemAlias;
  }

  public void setItemAlias(String itemAlias) {
    this.itemAlias = itemAlias;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentRepeat contentRepeat = (ContentRepeat) o;
    return Objects.equals(this.repeatFor, contentRepeat.repeatFor) &&
        Objects.equals(this.itemAlias, contentRepeat.itemAlias);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repeatFor, itemAlias);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentRepeat {\n");
    
    sb.append("    repeatFor: ").append(toIndentedString(repeatFor)).append("\n");
    sb.append("    itemAlias: ").append(toIndentedString(itemAlias)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
