/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-10-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * SegmentValuesRequestDTOResourceObjectAttributes
 */



public class SegmentValuesRequestDTOResourceObjectAttributes {
  /**
   * Defined segment reporting metric
   */
  @JsonAdapter(StatisticsEnum.Adapter.class)
  public enum StatisticsEnum {
    @SerializedName("members_added")
    MEMBERS_ADDED("members_added"),
    @SerializedName("members_removed")
    MEMBERS_REMOVED("members_removed"),
    @SerializedName("net_members_changed")
    NET_MEMBERS_CHANGED("net_members_changed"),
    @SerializedName("total_members")
    TOTAL_MEMBERS("total_members");

    private String value;

    StatisticsEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatisticsEnum fromValue(String input) {
      for (StatisticsEnum b : StatisticsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatisticsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatisticsEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StatisticsEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StatisticsEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("statistics")
  private List<StatisticsEnum> statistics = new ArrayList<StatisticsEnum>();

  @SerializedName("timeframe")
  private OneOfSegmentValuesRequestDTOResourceObjectAttributesTimeframe timeframe = null;

  @SerializedName("filter")
  private String filter = null;

  public SegmentValuesRequestDTOResourceObjectAttributes statistics(List<StatisticsEnum> statistics) {
    this.statistics = statistics;
    return this;
  }

  public SegmentValuesRequestDTOResourceObjectAttributes addStatisticsItem(StatisticsEnum statisticsItem) {
    this.statistics.add(statisticsItem);
    return this;
  }

   /**
   * List of statistics to query for.
   * @return statistics
  **/
  @Schema(example = "[\"total_members\",\"net_members_changed\"]", required = true, description = "List of statistics to query for.")
  public List<StatisticsEnum> getStatistics() {
    return statistics;
  }

  public void setStatistics(List<StatisticsEnum> statistics) {
    this.statistics = statistics;
  }

  public SegmentValuesRequestDTOResourceObjectAttributes timeframe(OneOfSegmentValuesRequestDTOResourceObjectAttributesTimeframe timeframe) {
    this.timeframe = timeframe;
    return this;
  }

   /**
   * The timeframe to query for data within. Data is unavailable before June 1st, 2023. Please use a timeframe after this date. The max length a timeframe can be is 1 year
   * @return timeframe
  **/
  @Schema(required = true, description = "The timeframe to query for data within. Data is unavailable before June 1st, 2023. Please use a timeframe after this date. The max length a timeframe can be is 1 year")
  public OneOfSegmentValuesRequestDTOResourceObjectAttributesTimeframe getTimeframe() {
    return timeframe;
  }

  public void setTimeframe(OneOfSegmentValuesRequestDTOResourceObjectAttributesTimeframe timeframe) {
    this.timeframe = timeframe;
  }

  public SegmentValuesRequestDTOResourceObjectAttributes filter(String filter) {
    this.filter = filter;
    return this;
  }

   /**
   * API filter string used to filter the query. Allowed filters are segment_id. Allowed operators are equals, any. Only one filter can be used per attribute. Max of 100 messages per ANY filter.
   * @return filter
  **/
  @Schema(example = "any(segment_id,[\"xyz123\",\"ghi456\"])", description = "API filter string used to filter the query. Allowed filters are segment_id. Allowed operators are equals, any. Only one filter can be used per attribute. Max of 100 messages per ANY filter.")
  public String getFilter() {
    return filter;
  }

  public void setFilter(String filter) {
    this.filter = filter;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SegmentValuesRequestDTOResourceObjectAttributes segmentValuesRequestDTOResourceObjectAttributes = (SegmentValuesRequestDTOResourceObjectAttributes) o;
    return Objects.equals(this.statistics, segmentValuesRequestDTOResourceObjectAttributes.statistics) &&
        Objects.equals(this.timeframe, segmentValuesRequestDTOResourceObjectAttributes.timeframe) &&
        Objects.equals(this.filter, segmentValuesRequestDTOResourceObjectAttributes.filter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statistics, timeframe, filter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SegmentValuesRequestDTOResourceObjectAttributes {\n");
    
    sb.append("    statistics: ").append(toIndentedString(statistics)).append("\n");
    sb.append("    timeframe: ").append(toIndentedString(timeframe)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
