/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2024-10-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * UniversalContentResponseObjectResourceAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-10-28T22:27:03.922311389Z[GMT]")

public class UniversalContentResponseObjectResourceAttributes {
  @SerializedName("name")
  private String name = null;

  @SerializedName("definition")
  private OneOfUniversalContentResponseObjectResourceAttributesDefinition definition = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("updated")
  private OffsetDateTime updated = null;

  /**
   * The status of a universal content screenshot.
   */
  @JsonAdapter(ScreenshotStatusEnum.Adapter.class)
  public enum ScreenshotStatusEnum {
    @SerializedName("completed")
    COMPLETED("completed"),
    @SerializedName("failed")
    FAILED("failed"),
    @SerializedName("generating")
    GENERATING("generating"),
    @SerializedName("never_generated")
    NEVER_GENERATED("never_generated"),
    @SerializedName("not_renderable")
    NOT_RENDERABLE("not_renderable");

    private String value;

    ScreenshotStatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ScreenshotStatusEnum fromValue(String input) {
      for (ScreenshotStatusEnum b : ScreenshotStatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ScreenshotStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ScreenshotStatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ScreenshotStatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ScreenshotStatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("screenshot_status")
  private ScreenshotStatusEnum screenshotStatus = null;

  @SerializedName("screenshot_url")
  private String screenshotUrl = null;

  public UniversalContentResponseObjectResourceAttributes name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name for this universal content
   * @return name
  **/
  @Schema(required = true, description = "The name for this universal content")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UniversalContentResponseObjectResourceAttributes definition(OneOfUniversalContentResponseObjectResourceAttributesDefinition definition) {
    this.definition = definition;
    return this;
  }

   /**
   * Get definition
   * @return definition
  **/
  @Schema(required = true, description = "")
  public OneOfUniversalContentResponseObjectResourceAttributesDefinition getDefinition() {
    return definition;
  }

  public void setDefinition(OneOfUniversalContentResponseObjectResourceAttributesDefinition definition) {
    this.definition = definition;
  }

  public UniversalContentResponseObjectResourceAttributes created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * The datetime when this universal content was created
   * @return created
  **/
  @Schema(example = "2022-11-08T00:00Z", required = true, description = "The datetime when this universal content was created")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public UniversalContentResponseObjectResourceAttributes updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * The datetime when this universal content was updated
   * @return updated
  **/
  @Schema(example = "2022-11-08T00:00Z", required = true, description = "The datetime when this universal content was updated")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }

  public UniversalContentResponseObjectResourceAttributes screenshotStatus(ScreenshotStatusEnum screenshotStatus) {
    this.screenshotStatus = screenshotStatus;
    return this;
  }

   /**
   * The status of a universal content screenshot.
   * @return screenshotStatus
  **/
  @Schema(required = true, description = "The status of a universal content screenshot.")
  public ScreenshotStatusEnum getScreenshotStatus() {
    return screenshotStatus;
  }

  public void setScreenshotStatus(ScreenshotStatusEnum screenshotStatus) {
    this.screenshotStatus = screenshotStatus;
  }

  public UniversalContentResponseObjectResourceAttributes screenshotUrl(String screenshotUrl) {
    this.screenshotUrl = screenshotUrl;
    return this;
  }

   /**
   * Get screenshotUrl
   * @return screenshotUrl
  **/
  @Schema(required = true, description = "")
  public String getScreenshotUrl() {
    return screenshotUrl;
  }

  public void setScreenshotUrl(String screenshotUrl) {
    this.screenshotUrl = screenshotUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UniversalContentResponseObjectResourceAttributes universalContentResponseObjectResourceAttributes = (UniversalContentResponseObjectResourceAttributes) o;
    return Objects.equals(this.name, universalContentResponseObjectResourceAttributes.name) &&
        Objects.equals(this.definition, universalContentResponseObjectResourceAttributes.definition) &&
        Objects.equals(this.created, universalContentResponseObjectResourceAttributes.created) &&
        Objects.equals(this.updated, universalContentResponseObjectResourceAttributes.updated) &&
        Objects.equals(this.screenshotStatus, universalContentResponseObjectResourceAttributes.screenshotStatus) &&
        Objects.equals(this.screenshotUrl, universalContentResponseObjectResourceAttributes.screenshotUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, definition, created, updated, screenshotStatus, screenshotUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UniversalContentResponseObjectResourceAttributes {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    screenshotStatus: ").append(toIndentedString(screenshotStatus)).append("\n");
    sb.append("    screenshotUrl: ").append(toIndentedString(screenshotUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
