/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;


import com.commercesystems.klaviyo_java.models.components.PostCouponCodeCreateJobResponse;
import com.commercesystems.klaviyo_java.utils.Response;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class BulkCreateCouponCodesResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Success
     */
    private Optional<? extends PostCouponCodeCreateJobResponse> postCouponCodeCreateJobResponse;

    @JsonCreator
    public BulkCreateCouponCodesResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends PostCouponCodeCreateJobResponse> postCouponCodeCreateJobResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(postCouponCodeCreateJobResponse, "postCouponCodeCreateJobResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.postCouponCodeCreateJobResponse = postCouponCodeCreateJobResponse;
    }
    
    public BulkCreateCouponCodesResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Success
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PostCouponCodeCreateJobResponse> postCouponCodeCreateJobResponse() {
        return (Optional<PostCouponCodeCreateJobResponse>) postCouponCodeCreateJobResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public BulkCreateCouponCodesResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public BulkCreateCouponCodesResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public BulkCreateCouponCodesResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Success
     */
    public BulkCreateCouponCodesResponse withPostCouponCodeCreateJobResponse(PostCouponCodeCreateJobResponse postCouponCodeCreateJobResponse) {
        Utils.checkNotNull(postCouponCodeCreateJobResponse, "postCouponCodeCreateJobResponse");
        this.postCouponCodeCreateJobResponse = Optional.ofNullable(postCouponCodeCreateJobResponse);
        return this;
    }

    /**
     * Success
     */
    public BulkCreateCouponCodesResponse withPostCouponCodeCreateJobResponse(Optional<? extends PostCouponCodeCreateJobResponse> postCouponCodeCreateJobResponse) {
        Utils.checkNotNull(postCouponCodeCreateJobResponse, "postCouponCodeCreateJobResponse");
        this.postCouponCodeCreateJobResponse = postCouponCodeCreateJobResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BulkCreateCouponCodesResponse other = (BulkCreateCouponCodesResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.postCouponCodeCreateJobResponse, other.postCouponCodeCreateJobResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            postCouponCodeCreateJobResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(BulkCreateCouponCodesResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "postCouponCodeCreateJobResponse", postCouponCodeCreateJobResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends PostCouponCodeCreateJobResponse> postCouponCodeCreateJobResponse = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Success
         */
        public Builder postCouponCodeCreateJobResponse(PostCouponCodeCreateJobResponse postCouponCodeCreateJobResponse) {
            Utils.checkNotNull(postCouponCodeCreateJobResponse, "postCouponCodeCreateJobResponse");
            this.postCouponCodeCreateJobResponse = Optional.ofNullable(postCouponCodeCreateJobResponse);
            return this;
        }

        /**
         * Success
         */
        public Builder postCouponCodeCreateJobResponse(Optional<? extends PostCouponCodeCreateJobResponse> postCouponCodeCreateJobResponse) {
            Utils.checkNotNull(postCouponCodeCreateJobResponse, "postCouponCodeCreateJobResponse");
            this.postCouponCodeCreateJobResponse = postCouponCodeCreateJobResponse;
            return this;
        }
        
        public BulkCreateCouponCodesResponse build() {
            return new BulkCreateCouponCodesResponse(
                contentType,
                statusCode,
                rawResponse,
                postCouponCodeCreateJobResponse);
        }
    }
}

