/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.models.components.TemplateCloneQuery;
import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;

public class CloneTemplateRequestBuilder {

    private String revision;
    private TemplateCloneQuery templateCloneQuery;
    private final SDKMethodInterfaces.MethodCallCloneTemplate sdk;

    public CloneTemplateRequestBuilder(SDKMethodInterfaces.MethodCallCloneTemplate sdk) {
        this.sdk = sdk;
    }

    public CloneTemplateRequestBuilder revision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }

    public CloneTemplateRequestBuilder templateCloneQuery(TemplateCloneQuery templateCloneQuery) {
        Utils.checkNotNull(templateCloneQuery, "templateCloneQuery");
        this.templateCloneQuery = templateCloneQuery;
        return this;
    }

    public CloneTemplateResponse call() throws Exception {
        if (revision == null) {
            revision = _SINGLETON_VALUE_Revision.value();
        }
        return sdk.cloneTemplate(
            revision,
            templateCloneQuery);
    }

    private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
            new LazySingletonValue<>(
                    "revision",
                    "\"2024-10-15\"",
                    new TypeReference<String>() {});
}
