/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;


import com.commercesystems.klaviyo_java.models.components.PostProfileResponse;
import com.commercesystems.klaviyo_java.utils.Response;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class CreateOrUpdateProfileResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Profile Updated Successfully
     */
    private Optional<? extends PostProfileResponse> postProfileResponse;

    @JsonCreator
    public CreateOrUpdateProfileResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends PostProfileResponse> postProfileResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(postProfileResponse, "postProfileResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.postProfileResponse = postProfileResponse;
    }
    
    public CreateOrUpdateProfileResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Profile Updated Successfully
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PostProfileResponse> postProfileResponse() {
        return (Optional<PostProfileResponse>) postProfileResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public CreateOrUpdateProfileResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateOrUpdateProfileResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateOrUpdateProfileResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Profile Updated Successfully
     */
    public CreateOrUpdateProfileResponse withPostProfileResponse(PostProfileResponse postProfileResponse) {
        Utils.checkNotNull(postProfileResponse, "postProfileResponse");
        this.postProfileResponse = Optional.ofNullable(postProfileResponse);
        return this;
    }

    /**
     * Profile Updated Successfully
     */
    public CreateOrUpdateProfileResponse withPostProfileResponse(Optional<? extends PostProfileResponse> postProfileResponse) {
        Utils.checkNotNull(postProfileResponse, "postProfileResponse");
        this.postProfileResponse = postProfileResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateOrUpdateProfileResponse other = (CreateOrUpdateProfileResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.postProfileResponse, other.postProfileResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            postProfileResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateOrUpdateProfileResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "postProfileResponse", postProfileResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends PostProfileResponse> postProfileResponse = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Profile Updated Successfully
         */
        public Builder postProfileResponse(PostProfileResponse postProfileResponse) {
            Utils.checkNotNull(postProfileResponse, "postProfileResponse");
            this.postProfileResponse = Optional.ofNullable(postProfileResponse);
            return this;
        }

        /**
         * Profile Updated Successfully
         */
        public Builder postProfileResponse(Optional<? extends PostProfileResponse> postProfileResponse) {
            Utils.checkNotNull(postProfileResponse, "postProfileResponse");
            this.postProfileResponse = postProfileResponse;
            return this;
        }
        
        public CreateOrUpdateProfileResponse build() {
            return new CreateOrUpdateProfileResponse(
                contentType,
                statusCode,
                rawResponse,
                postProfileResponse);
        }
    }
}

