/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.models.components.ServerBISSubscriptionCreateQuery;
import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;

public class CreateBackInStockSubscriptionRequestBuilder {

    private String revision;
    private ServerBISSubscriptionCreateQuery serverBISSubscriptionCreateQuery;
    private final SDKMethodInterfaces.MethodCallCreateBackInStockSubscription sdk;

    public CreateBackInStockSubscriptionRequestBuilder(SDKMethodInterfaces.MethodCallCreateBackInStockSubscription sdk) {
        this.sdk = sdk;
    }

    public CreateBackInStockSubscriptionRequestBuilder revision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }

    public CreateBackInStockSubscriptionRequestBuilder serverBISSubscriptionCreateQuery(ServerBISSubscriptionCreateQuery serverBISSubscriptionCreateQuery) {
        Utils.checkNotNull(serverBISSubscriptionCreateQuery, "serverBISSubscriptionCreateQuery");
        this.serverBISSubscriptionCreateQuery = serverBISSubscriptionCreateQuery;
        return this;
    }

    public CreateBackInStockSubscriptionResponse call() throws Exception {
        if (revision == null) {
            revision = _SINGLETON_VALUE_Revision.value();
        }
        return sdk.createBackInStockSubscription(
            revision,
            serverBISSubscriptionCreateQuery);
    }

    private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
            new LazySingletonValue<>(
                    "revision",
                    "\"2024-10-15\"",
                    new TypeReference<String>() {});
}
