/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.utils.Utils;

public class GetCatalogVariantsRequestBuilder {

    private GetCatalogVariantsRequest request;
    private final SDKMethodInterfaces.MethodCallGetCatalogVariants sdk;

    public GetCatalogVariantsRequestBuilder(SDKMethodInterfaces.MethodCallGetCatalogVariants sdk) {
        this.sdk = sdk;
    }

    public GetCatalogVariantsRequestBuilder request(GetCatalogVariantsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetCatalogVariantsResponse call() throws Exception {

        return sdk.getCatalogVariants(
            request);
    }
}
