/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;


import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.SpeakeasyMetadata;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class GetEventsRequest {

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=fields[event]")
    private Optional<? extends List<FieldsEvent>> fieldsEvent;

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=fields[metric]")
    private Optional<? extends List<FieldsMetric>> fieldsMetric;

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=fields[profile]")
    private Optional<? extends List<FieldsProfile>> fieldsProfile;

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#filtering&lt;br&gt;Allowed field(s)/operator(s):&lt;br&gt;`metric_id`: `equals`&lt;br&gt;`profile_id`: `equals`&lt;br&gt;`profile`: `has`&lt;br&gt;`datetime`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`&lt;br&gt;`timestamp`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")
    private Optional<String> filter;

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#relationships
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=include")
    private Optional<? extends List<GetEventsQueryParamInclude>> include;

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#pagination
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page[cursor]")
    private Optional<String> pageCursor;

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sorting
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")
    private Optional<? extends GetEventsQueryParamSort> sort;

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=revision")
    private String revision;

    @JsonCreator
    public GetEventsRequest(
            Optional<? extends List<FieldsEvent>> fieldsEvent,
            Optional<? extends List<FieldsMetric>> fieldsMetric,
            Optional<? extends List<FieldsProfile>> fieldsProfile,
            Optional<String> filter,
            Optional<? extends List<GetEventsQueryParamInclude>> include,
            Optional<String> pageCursor,
            Optional<? extends GetEventsQueryParamSort> sort,
            String revision) {
        Utils.checkNotNull(fieldsEvent, "fieldsEvent");
        Utils.checkNotNull(fieldsMetric, "fieldsMetric");
        Utils.checkNotNull(fieldsProfile, "fieldsProfile");
        Utils.checkNotNull(filter, "filter");
        Utils.checkNotNull(include, "include");
        Utils.checkNotNull(pageCursor, "pageCursor");
        Utils.checkNotNull(sort, "sort");
        Utils.checkNotNull(revision, "revision");
        this.fieldsEvent = fieldsEvent;
        this.fieldsMetric = fieldsMetric;
        this.fieldsProfile = fieldsProfile;
        this.filter = filter;
        this.include = include;
        this.pageCursor = pageCursor;
        this.sort = sort;
        this.revision = revision;
    }
    
    public GetEventsRequest(
            String revision) {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), revision);
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<FieldsEvent>> fieldsEvent() {
        return (Optional<List<FieldsEvent>>) fieldsEvent;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<FieldsMetric>> fieldsMetric() {
        return (Optional<List<FieldsMetric>>) fieldsMetric;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<FieldsProfile>> fieldsProfile() {
        return (Optional<List<FieldsProfile>>) fieldsProfile;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#filtering&lt;br&gt;Allowed field(s)/operator(s):&lt;br&gt;`metric_id`: `equals`&lt;br&gt;`profile_id`: `equals`&lt;br&gt;`profile`: `has`&lt;br&gt;`datetime`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`&lt;br&gt;`timestamp`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`
     */
    @JsonIgnore
    public Optional<String> filter() {
        return filter;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#relationships
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<GetEventsQueryParamInclude>> include() {
        return (Optional<List<GetEventsQueryParamInclude>>) include;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#pagination
     */
    @JsonIgnore
    public Optional<String> pageCursor() {
        return pageCursor;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sorting
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetEventsQueryParamSort> sort() {
        return (Optional<GetEventsQueryParamSort>) sort;
    }

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    @JsonIgnore
    public String revision() {
        return revision;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    public GetEventsRequest withFieldsEvent(List<FieldsEvent> fieldsEvent) {
        Utils.checkNotNull(fieldsEvent, "fieldsEvent");
        this.fieldsEvent = Optional.ofNullable(fieldsEvent);
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    public GetEventsRequest withFieldsEvent(Optional<? extends List<FieldsEvent>> fieldsEvent) {
        Utils.checkNotNull(fieldsEvent, "fieldsEvent");
        this.fieldsEvent = fieldsEvent;
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    public GetEventsRequest withFieldsMetric(List<FieldsMetric> fieldsMetric) {
        Utils.checkNotNull(fieldsMetric, "fieldsMetric");
        this.fieldsMetric = Optional.ofNullable(fieldsMetric);
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    public GetEventsRequest withFieldsMetric(Optional<? extends List<FieldsMetric>> fieldsMetric) {
        Utils.checkNotNull(fieldsMetric, "fieldsMetric");
        this.fieldsMetric = fieldsMetric;
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    public GetEventsRequest withFieldsProfile(List<FieldsProfile> fieldsProfile) {
        Utils.checkNotNull(fieldsProfile, "fieldsProfile");
        this.fieldsProfile = Optional.ofNullable(fieldsProfile);
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    public GetEventsRequest withFieldsProfile(Optional<? extends List<FieldsProfile>> fieldsProfile) {
        Utils.checkNotNull(fieldsProfile, "fieldsProfile");
        this.fieldsProfile = fieldsProfile;
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#filtering&lt;br&gt;Allowed field(s)/operator(s):&lt;br&gt;`metric_id`: `equals`&lt;br&gt;`profile_id`: `equals`&lt;br&gt;`profile`: `has`&lt;br&gt;`datetime`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`&lt;br&gt;`timestamp`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`
     */
    public GetEventsRequest withFilter(String filter) {
        Utils.checkNotNull(filter, "filter");
        this.filter = Optional.ofNullable(filter);
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#filtering&lt;br&gt;Allowed field(s)/operator(s):&lt;br&gt;`metric_id`: `equals`&lt;br&gt;`profile_id`: `equals`&lt;br&gt;`profile`: `has`&lt;br&gt;`datetime`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`&lt;br&gt;`timestamp`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`
     */
    public GetEventsRequest withFilter(Optional<String> filter) {
        Utils.checkNotNull(filter, "filter");
        this.filter = filter;
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#relationships
     */
    public GetEventsRequest withInclude(List<GetEventsQueryParamInclude> include) {
        Utils.checkNotNull(include, "include");
        this.include = Optional.ofNullable(include);
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#relationships
     */
    public GetEventsRequest withInclude(Optional<? extends List<GetEventsQueryParamInclude>> include) {
        Utils.checkNotNull(include, "include");
        this.include = include;
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#pagination
     */
    public GetEventsRequest withPageCursor(String pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = Optional.ofNullable(pageCursor);
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#pagination
     */
    public GetEventsRequest withPageCursor(Optional<String> pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = pageCursor;
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sorting
     */
    public GetEventsRequest withSort(GetEventsQueryParamSort sort) {
        Utils.checkNotNull(sort, "sort");
        this.sort = Optional.ofNullable(sort);
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sorting
     */
    public GetEventsRequest withSort(Optional<? extends GetEventsQueryParamSort> sort) {
        Utils.checkNotNull(sort, "sort");
        this.sort = sort;
        return this;
    }

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    public GetEventsRequest withRevision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetEventsRequest other = (GetEventsRequest) o;
        return 
            Objects.deepEquals(this.fieldsEvent, other.fieldsEvent) &&
            Objects.deepEquals(this.fieldsMetric, other.fieldsMetric) &&
            Objects.deepEquals(this.fieldsProfile, other.fieldsProfile) &&
            Objects.deepEquals(this.filter, other.filter) &&
            Objects.deepEquals(this.include, other.include) &&
            Objects.deepEquals(this.pageCursor, other.pageCursor) &&
            Objects.deepEquals(this.sort, other.sort) &&
            Objects.deepEquals(this.revision, other.revision);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            fieldsEvent,
            fieldsMetric,
            fieldsProfile,
            filter,
            include,
            pageCursor,
            sort,
            revision);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetEventsRequest.class,
                "fieldsEvent", fieldsEvent,
                "fieldsMetric", fieldsMetric,
                "fieldsProfile", fieldsProfile,
                "filter", filter,
                "include", include,
                "pageCursor", pageCursor,
                "sort", sort,
                "revision", revision);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<FieldsEvent>> fieldsEvent = Optional.empty();
 
        private Optional<? extends List<FieldsMetric>> fieldsMetric = Optional.empty();
 
        private Optional<? extends List<FieldsProfile>> fieldsProfile = Optional.empty();
 
        private Optional<String> filter = Optional.empty();
 
        private Optional<? extends List<GetEventsQueryParamInclude>> include = Optional.empty();
 
        private Optional<String> pageCursor = Optional.empty();
 
        private Optional<? extends GetEventsQueryParamSort> sort = Optional.empty();
 
        private String revision;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
         */
        public Builder fieldsEvent(List<FieldsEvent> fieldsEvent) {
            Utils.checkNotNull(fieldsEvent, "fieldsEvent");
            this.fieldsEvent = Optional.ofNullable(fieldsEvent);
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
         */
        public Builder fieldsEvent(Optional<? extends List<FieldsEvent>> fieldsEvent) {
            Utils.checkNotNull(fieldsEvent, "fieldsEvent");
            this.fieldsEvent = fieldsEvent;
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
         */
        public Builder fieldsMetric(List<FieldsMetric> fieldsMetric) {
            Utils.checkNotNull(fieldsMetric, "fieldsMetric");
            this.fieldsMetric = Optional.ofNullable(fieldsMetric);
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
         */
        public Builder fieldsMetric(Optional<? extends List<FieldsMetric>> fieldsMetric) {
            Utils.checkNotNull(fieldsMetric, "fieldsMetric");
            this.fieldsMetric = fieldsMetric;
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
         */
        public Builder fieldsProfile(List<FieldsProfile> fieldsProfile) {
            Utils.checkNotNull(fieldsProfile, "fieldsProfile");
            this.fieldsProfile = Optional.ofNullable(fieldsProfile);
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
         */
        public Builder fieldsProfile(Optional<? extends List<FieldsProfile>> fieldsProfile) {
            Utils.checkNotNull(fieldsProfile, "fieldsProfile");
            this.fieldsProfile = fieldsProfile;
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#filtering&lt;br&gt;Allowed field(s)/operator(s):&lt;br&gt;`metric_id`: `equals`&lt;br&gt;`profile_id`: `equals`&lt;br&gt;`profile`: `has`&lt;br&gt;`datetime`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`&lt;br&gt;`timestamp`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`
         */
        public Builder filter(String filter) {
            Utils.checkNotNull(filter, "filter");
            this.filter = Optional.ofNullable(filter);
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#filtering&lt;br&gt;Allowed field(s)/operator(s):&lt;br&gt;`metric_id`: `equals`&lt;br&gt;`profile_id`: `equals`&lt;br&gt;`profile`: `has`&lt;br&gt;`datetime`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`&lt;br&gt;`timestamp`: `greater-or-equal`, `greater-than`, `less-or-equal`, `less-than`
         */
        public Builder filter(Optional<String> filter) {
            Utils.checkNotNull(filter, "filter");
            this.filter = filter;
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#relationships
         */
        public Builder include(List<GetEventsQueryParamInclude> include) {
            Utils.checkNotNull(include, "include");
            this.include = Optional.ofNullable(include);
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#relationships
         */
        public Builder include(Optional<? extends List<GetEventsQueryParamInclude>> include) {
            Utils.checkNotNull(include, "include");
            this.include = include;
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#pagination
         */
        public Builder pageCursor(String pageCursor) {
            Utils.checkNotNull(pageCursor, "pageCursor");
            this.pageCursor = Optional.ofNullable(pageCursor);
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#pagination
         */
        public Builder pageCursor(Optional<String> pageCursor) {
            Utils.checkNotNull(pageCursor, "pageCursor");
            this.pageCursor = pageCursor;
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sorting
         */
        public Builder sort(GetEventsQueryParamSort sort) {
            Utils.checkNotNull(sort, "sort");
            this.sort = Optional.ofNullable(sort);
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sorting
         */
        public Builder sort(Optional<? extends GetEventsQueryParamSort> sort) {
            Utils.checkNotNull(sort, "sort");
            this.sort = sort;
            return this;
        }

        /**
         * API endpoint revision (format: YYYY-MM-DD[.suffix])
         */
        public Builder revision(String revision) {
            Utils.checkNotNull(revision, "revision");
            this.revision = revision;
            return this;
        }
        
        public GetEventsRequest build() {
            if (revision == null) {
                revision = _SINGLETON_VALUE_Revision.value();
            }            return new GetEventsRequest(
                fieldsEvent,
                fieldsMetric,
                fieldsProfile,
                filter,
                include,
                pageCursor,
                sort,
                revision);
        }

        private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
                new LazySingletonValue<>(
                        "revision",
                        "\"2024-10-15\"",
                        new TypeReference<String>() {});
    }
}

