/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum GetFlowMessageQueryParamFieldsTemplate {
    NAME("name"),
    EDITOR_TYPE("editor_type"),
    HTML("html"),
    TEXT("text"),
    CREATED("created"),
    UPDATED("updated");

    @JsonValue
    private final String value;

    private GetFlowMessageQueryParamFieldsTemplate(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
