/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;
import java.util.List;
import java.util.Optional;

public class GetFlowActionFlowRequestBuilder {

    private String id;
    private Optional<? extends List<GetFlowActionFlowQueryParamFieldsFlow>> fieldsFlow = Optional.empty();
    private String revision;
    private final SDKMethodInterfaces.MethodCallGetFlowActionFlow sdk;

    public GetFlowActionFlowRequestBuilder(SDKMethodInterfaces.MethodCallGetFlowActionFlow sdk) {
        this.sdk = sdk;
    }

    public GetFlowActionFlowRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }
                
    public GetFlowActionFlowRequestBuilder fieldsFlow(List<GetFlowActionFlowQueryParamFieldsFlow> fieldsFlow) {
        Utils.checkNotNull(fieldsFlow, "fieldsFlow");
        this.fieldsFlow = Optional.of(fieldsFlow);
        return this;
    }

    public GetFlowActionFlowRequestBuilder fieldsFlow(Optional<? extends List<GetFlowActionFlowQueryParamFieldsFlow>> fieldsFlow) {
        Utils.checkNotNull(fieldsFlow, "fieldsFlow");
        this.fieldsFlow = fieldsFlow;
        return this;
    }

    public GetFlowActionFlowRequestBuilder revision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }

    public GetFlowActionFlowResponse call() throws Exception {
        if (revision == null) {
            revision = _SINGLETON_VALUE_Revision.value();
        }
        return sdk.getFlowActionFlow(
            id,
            fieldsFlow,
            revision);
    }

    private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
            new LazySingletonValue<>(
                    "revision",
                    "\"2024-10-15\"",
                    new TypeReference<String>() {});
}
