/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.utils.Utils;

public class GetListsRequestBuilder {

    private GetListsRequest request;
    private final SDKMethodInterfaces.MethodCallGetLists sdk;

    public GetListsRequestBuilder(SDKMethodInterfaces.MethodCallGetLists sdk) {
        this.sdk = sdk;
    }

    public GetListsRequestBuilder request(GetListsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetListsResponse call() throws Exception {

        return sdk.getLists(
            request);
    }
}
