/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;


import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.SpeakeasyMetadata;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class GetTrackingSettingRequest {

    /**
     * The id of the tracking setting (account ID).
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=fields[tracking-setting]")
    private Optional<? extends List<QueryParamFieldsTrackingSetting>> fieldsTrackingSetting;

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=revision")
    private String revision;

    @JsonCreator
    public GetTrackingSettingRequest(
            String id,
            Optional<? extends List<QueryParamFieldsTrackingSetting>> fieldsTrackingSetting,
            String revision) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(fieldsTrackingSetting, "fieldsTrackingSetting");
        Utils.checkNotNull(revision, "revision");
        this.id = id;
        this.fieldsTrackingSetting = fieldsTrackingSetting;
        this.revision = revision;
    }
    
    public GetTrackingSettingRequest(
            String id,
            String revision) {
        this(id, Optional.empty(), revision);
    }

    /**
     * The id of the tracking setting (account ID).
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<QueryParamFieldsTrackingSetting>> fieldsTrackingSetting() {
        return (Optional<List<QueryParamFieldsTrackingSetting>>) fieldsTrackingSetting;
    }

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    @JsonIgnore
    public String revision() {
        return revision;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The id of the tracking setting (account ID).
     */
    public GetTrackingSettingRequest withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    public GetTrackingSettingRequest withFieldsTrackingSetting(List<QueryParamFieldsTrackingSetting> fieldsTrackingSetting) {
        Utils.checkNotNull(fieldsTrackingSetting, "fieldsTrackingSetting");
        this.fieldsTrackingSetting = Optional.ofNullable(fieldsTrackingSetting);
        return this;
    }

    /**
     * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
     */
    public GetTrackingSettingRequest withFieldsTrackingSetting(Optional<? extends List<QueryParamFieldsTrackingSetting>> fieldsTrackingSetting) {
        Utils.checkNotNull(fieldsTrackingSetting, "fieldsTrackingSetting");
        this.fieldsTrackingSetting = fieldsTrackingSetting;
        return this;
    }

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    public GetTrackingSettingRequest withRevision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTrackingSettingRequest other = (GetTrackingSettingRequest) o;
        return 
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.fieldsTrackingSetting, other.fieldsTrackingSetting) &&
            Objects.deepEquals(this.revision, other.revision);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            id,
            fieldsTrackingSetting,
            revision);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTrackingSettingRequest.class,
                "id", id,
                "fieldsTrackingSetting", fieldsTrackingSetting,
                "revision", revision);
    }
    
    public final static class Builder {
 
        private String id;
 
        private Optional<? extends List<QueryParamFieldsTrackingSetting>> fieldsTrackingSetting = Optional.empty();
 
        private String revision;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The id of the tracking setting (account ID).
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
         */
        public Builder fieldsTrackingSetting(List<QueryParamFieldsTrackingSetting> fieldsTrackingSetting) {
            Utils.checkNotNull(fieldsTrackingSetting, "fieldsTrackingSetting");
            this.fieldsTrackingSetting = Optional.ofNullable(fieldsTrackingSetting);
            return this;
        }

        /**
         * For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sparse-fieldsets
         */
        public Builder fieldsTrackingSetting(Optional<? extends List<QueryParamFieldsTrackingSetting>> fieldsTrackingSetting) {
            Utils.checkNotNull(fieldsTrackingSetting, "fieldsTrackingSetting");
            this.fieldsTrackingSetting = fieldsTrackingSetting;
            return this;
        }

        /**
         * API endpoint revision (format: YYYY-MM-DD[.suffix])
         */
        public Builder revision(String revision) {
            Utils.checkNotNull(revision, "revision");
            this.revision = revision;
            return this;
        }
        
        public GetTrackingSettingRequest build() {
            if (revision == null) {
                revision = _SINGLETON_VALUE_Revision.value();
            }            return new GetTrackingSettingRequest(
                id,
                fieldsTrackingSetting,
                revision);
        }

        private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
                new LazySingletonValue<>(
                        "revision",
                        "\"2024-10-15\"",
                        new TypeReference<String>() {});
    }
}

