/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.utils.Utils;

public class GetTagGroupsRequestBuilder {

    private GetTagGroupsRequest request;
    private final SDKMethodInterfaces.MethodCallGetTagGroups sdk;

    public GetTagGroupsRequestBuilder(SDKMethodInterfaces.MethodCallGetTagGroups sdk) {
        this.sdk = sdk;
    }

    public GetTagGroupsRequestBuilder request(GetTagGroupsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetTagGroupsResponse call() throws Exception {

        return sdk.getTagGroups(
            request);
    }
}
