/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * GetTagGroupsQueryParamSort - For more information please visit https://developers.klaviyo.com/en/v2024-10-15/reference/api-overview#sorting
 */
public enum GetTagGroupsQueryParamSort {
    ID("id"),
    MINUS_ID("-id"),
    NAME("name"),
    MINUS_NAME("-name");

    @JsonValue
    private final String value;

    private GetTagGroupsQueryParamSort(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
