/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum GetVersionsForFormQueryParamFieldsFormVersion {
    FORM_TYPE("form_type"),
    AB_TEST("ab_test"),
    AB_TEST_VARIATION_NAME("ab_test.variation_name"),
    STATUS("status"),
    CREATED_AT("created_at"),
    UPDATED_AT("updated_at");

    @JsonValue
    private final String value;

    private GetVersionsForFormQueryParamFieldsFormVersion(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
