/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum QueryParamFieldsCouponCode {
    UNIQUE_CODE("unique_code"),
    EXPIRES_AT("expires_at"),
    STATUS("status");

    @JsonValue
    private final String value;

    private QueryParamFieldsCouponCode(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
