/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.models.components.FormValuesRequestDTO;
import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;

public class QueryFormValuesRequestBuilder {

    private String revision;
    private FormValuesRequestDTO formValuesRequestDTO;
    private final SDKMethodInterfaces.MethodCallQueryFormValues sdk;

    public QueryFormValuesRequestBuilder(SDKMethodInterfaces.MethodCallQueryFormValues sdk) {
        this.sdk = sdk;
    }

    public QueryFormValuesRequestBuilder revision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }

    public QueryFormValuesRequestBuilder formValuesRequestDTO(FormValuesRequestDTO formValuesRequestDTO) {
        Utils.checkNotNull(formValuesRequestDTO, "formValuesRequestDTO");
        this.formValuesRequestDTO = formValuesRequestDTO;
        return this;
    }

    public QueryFormValuesResponse call() throws Exception {
        if (revision == null) {
            revision = _SINGLETON_VALUE_Revision.value();
        }
        return sdk.queryFormValues(
            revision,
            formValuesRequestDTO);
    }

    private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
            new LazySingletonValue<>(
                    "revision",
                    "\"2024-10-15\"",
                    new TypeReference<String>() {});
}
