/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.models.components.PushTokenUnregisterQuery;
import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;

public class UnregisterClientPushTokenRequestBuilder {

    private String companyId;
    private String revision;
    private PushTokenUnregisterQuery pushTokenUnregisterQuery;
    private final SDKMethodInterfaces.MethodCallUnregisterClientPushToken sdk;

    public UnregisterClientPushTokenRequestBuilder(SDKMethodInterfaces.MethodCallUnregisterClientPushToken sdk) {
        this.sdk = sdk;
    }

    public UnregisterClientPushTokenRequestBuilder companyId(String companyId) {
        Utils.checkNotNull(companyId, "companyId");
        this.companyId = companyId;
        return this;
    }

    public UnregisterClientPushTokenRequestBuilder revision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }

    public UnregisterClientPushTokenRequestBuilder pushTokenUnregisterQuery(PushTokenUnregisterQuery pushTokenUnregisterQuery) {
        Utils.checkNotNull(pushTokenUnregisterQuery, "pushTokenUnregisterQuery");
        this.pushTokenUnregisterQuery = pushTokenUnregisterQuery;
        return this;
    }

    public UnregisterClientPushTokenResponse call() throws Exception {
        if (revision == null) {
            revision = _SINGLETON_VALUE_Revision.value();
        }
        return sdk.unregisterClientPushToken(
            companyId,
            revision,
            pushTokenUnregisterQuery);
    }

    private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
            new LazySingletonValue<>(
                    "revision",
                    "\"2024-10-15\"",
                    new TypeReference<String>() {});
}
