/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;

import com.commercesystems.klaviyo_java.models.components.CampaignMessagePartialUpdateQuery;
import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.String;

public class UpdateCampaignMessageRequestBuilder {

    private String id;
    private String revision;
    private CampaignMessagePartialUpdateQuery campaignMessagePartialUpdateQuery;
    private final SDKMethodInterfaces.MethodCallUpdateCampaignMessage sdk;

    public UpdateCampaignMessageRequestBuilder(SDKMethodInterfaces.MethodCallUpdateCampaignMessage sdk) {
        this.sdk = sdk;
    }

    public UpdateCampaignMessageRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public UpdateCampaignMessageRequestBuilder revision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }

    public UpdateCampaignMessageRequestBuilder campaignMessagePartialUpdateQuery(CampaignMessagePartialUpdateQuery campaignMessagePartialUpdateQuery) {
        Utils.checkNotNull(campaignMessagePartialUpdateQuery, "campaignMessagePartialUpdateQuery");
        this.campaignMessagePartialUpdateQuery = campaignMessagePartialUpdateQuery;
        return this;
    }

    public UpdateCampaignMessageResponse call() throws Exception {
        if (revision == null) {
            revision = _SINGLETON_VALUE_Revision.value();
        }
        return sdk.updateCampaignMessage(
            id,
            revision,
            campaignMessagePartialUpdateQuery);
    }

    private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
            new LazySingletonValue<>(
                    "revision",
                    "\"2024-10-15\"",
                    new TypeReference<String>() {});
}
