/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.commercesystems.klaviyo_java.models.operations;


import com.commercesystems.klaviyo_java.models.components.ProfilePartialUpdateQuery;
import com.commercesystems.klaviyo_java.utils.LazySingletonValue;
import com.commercesystems.klaviyo_java.utils.SpeakeasyMetadata;
import com.commercesystems.klaviyo_java.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class UpdateProfileRequest {

    /**
     * Primary key that uniquely identifies this profile. Generated by Klaviyo.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    /**
     * Request additional fields not included by default in the response. Supported values: 'subscriptions', 'predictive_analytics'
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=additional-fields[profile]")
    private Optional<? extends List<UpdateProfileQueryParamAdditionalFieldsProfile>> additionalFieldsProfile;

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=revision")
    private String revision;

    @SpeakeasyMetadata("request:mediaType=application/vnd.api+json")
    private ProfilePartialUpdateQuery profilePartialUpdateQuery;

    @JsonCreator
    public UpdateProfileRequest(
            String id,
            Optional<? extends List<UpdateProfileQueryParamAdditionalFieldsProfile>> additionalFieldsProfile,
            String revision,
            ProfilePartialUpdateQuery profilePartialUpdateQuery) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(additionalFieldsProfile, "additionalFieldsProfile");
        Utils.checkNotNull(revision, "revision");
        Utils.checkNotNull(profilePartialUpdateQuery, "profilePartialUpdateQuery");
        this.id = id;
        this.additionalFieldsProfile = additionalFieldsProfile;
        this.revision = revision;
        this.profilePartialUpdateQuery = profilePartialUpdateQuery;
    }
    
    public UpdateProfileRequest(
            String id,
            String revision,
            ProfilePartialUpdateQuery profilePartialUpdateQuery) {
        this(id, Optional.empty(), revision, profilePartialUpdateQuery);
    }

    /**
     * Primary key that uniquely identifies this profile. Generated by Klaviyo.
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    /**
     * Request additional fields not included by default in the response. Supported values: 'subscriptions', 'predictive_analytics'
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<UpdateProfileQueryParamAdditionalFieldsProfile>> additionalFieldsProfile() {
        return (Optional<List<UpdateProfileQueryParamAdditionalFieldsProfile>>) additionalFieldsProfile;
    }

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    @JsonIgnore
    public String revision() {
        return revision;
    }

    @JsonIgnore
    public ProfilePartialUpdateQuery profilePartialUpdateQuery() {
        return profilePartialUpdateQuery;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Primary key that uniquely identifies this profile. Generated by Klaviyo.
     */
    public UpdateProfileRequest withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * Request additional fields not included by default in the response. Supported values: 'subscriptions', 'predictive_analytics'
     */
    public UpdateProfileRequest withAdditionalFieldsProfile(List<UpdateProfileQueryParamAdditionalFieldsProfile> additionalFieldsProfile) {
        Utils.checkNotNull(additionalFieldsProfile, "additionalFieldsProfile");
        this.additionalFieldsProfile = Optional.ofNullable(additionalFieldsProfile);
        return this;
    }

    /**
     * Request additional fields not included by default in the response. Supported values: 'subscriptions', 'predictive_analytics'
     */
    public UpdateProfileRequest withAdditionalFieldsProfile(Optional<? extends List<UpdateProfileQueryParamAdditionalFieldsProfile>> additionalFieldsProfile) {
        Utils.checkNotNull(additionalFieldsProfile, "additionalFieldsProfile");
        this.additionalFieldsProfile = additionalFieldsProfile;
        return this;
    }

    /**
     * API endpoint revision (format: YYYY-MM-DD[.suffix])
     */
    public UpdateProfileRequest withRevision(String revision) {
        Utils.checkNotNull(revision, "revision");
        this.revision = revision;
        return this;
    }

    public UpdateProfileRequest withProfilePartialUpdateQuery(ProfilePartialUpdateQuery profilePartialUpdateQuery) {
        Utils.checkNotNull(profilePartialUpdateQuery, "profilePartialUpdateQuery");
        this.profilePartialUpdateQuery = profilePartialUpdateQuery;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateProfileRequest other = (UpdateProfileRequest) o;
        return 
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.additionalFieldsProfile, other.additionalFieldsProfile) &&
            Objects.deepEquals(this.revision, other.revision) &&
            Objects.deepEquals(this.profilePartialUpdateQuery, other.profilePartialUpdateQuery);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            id,
            additionalFieldsProfile,
            revision,
            profilePartialUpdateQuery);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateProfileRequest.class,
                "id", id,
                "additionalFieldsProfile", additionalFieldsProfile,
                "revision", revision,
                "profilePartialUpdateQuery", profilePartialUpdateQuery);
    }
    
    public final static class Builder {
 
        private String id;
 
        private Optional<? extends List<UpdateProfileQueryParamAdditionalFieldsProfile>> additionalFieldsProfile = Optional.empty();
 
        private String revision;
 
        private ProfilePartialUpdateQuery profilePartialUpdateQuery;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Primary key that uniquely identifies this profile. Generated by Klaviyo.
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * Request additional fields not included by default in the response. Supported values: 'subscriptions', 'predictive_analytics'
         */
        public Builder additionalFieldsProfile(List<UpdateProfileQueryParamAdditionalFieldsProfile> additionalFieldsProfile) {
            Utils.checkNotNull(additionalFieldsProfile, "additionalFieldsProfile");
            this.additionalFieldsProfile = Optional.ofNullable(additionalFieldsProfile);
            return this;
        }

        /**
         * Request additional fields not included by default in the response. Supported values: 'subscriptions', 'predictive_analytics'
         */
        public Builder additionalFieldsProfile(Optional<? extends List<UpdateProfileQueryParamAdditionalFieldsProfile>> additionalFieldsProfile) {
            Utils.checkNotNull(additionalFieldsProfile, "additionalFieldsProfile");
            this.additionalFieldsProfile = additionalFieldsProfile;
            return this;
        }

        /**
         * API endpoint revision (format: YYYY-MM-DD[.suffix])
         */
        public Builder revision(String revision) {
            Utils.checkNotNull(revision, "revision");
            this.revision = revision;
            return this;
        }

        public Builder profilePartialUpdateQuery(ProfilePartialUpdateQuery profilePartialUpdateQuery) {
            Utils.checkNotNull(profilePartialUpdateQuery, "profilePartialUpdateQuery");
            this.profilePartialUpdateQuery = profilePartialUpdateQuery;
            return this;
        }
        
        public UpdateProfileRequest build() {
            if (revision == null) {
                revision = _SINGLETON_VALUE_Revision.value();
            }            return new UpdateProfileRequest(
                id,
                additionalFieldsProfile,
                revision,
                profilePartialUpdateQuery);
        }

        private static final LazySingletonValue<String> _SINGLETON_VALUE_Revision =
                new LazySingletonValue<>(
                        "revision",
                        "\"2024-10-15\"",
                        new TypeReference<String>() {});
    }
}

